#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqExercises.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NORTHWND")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NORTHWNDConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MyClass> MyClasses
		{
			get
			{
				return this.GetTable<MyClass>();
			}
		}
		
		public System.Data.Linq.Table<MyClass2> MyClass2s
		{
			get
			{
				return this.GetTable<MyClass2>();
			}
		}
		
		public System.Data.Linq.Table<MyClass3> MyClass3s
		{
			get
			{
				return this.GetTable<MyClass3>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class MyClass
	{
		
		private System.Nullable<int> _Shipper;
		
		private System.Nullable<decimal> _FreightTotals;
		
		public MyClass()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shipper")]
		public System.Nullable<int> Shipper
		{
			get
			{
				return this._Shipper;
			}
			set
			{
				if ((this._Shipper != value))
				{
					this._Shipper = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FreightTotals")]
		public System.Nullable<decimal> FreightTotals
		{
			get
			{
				return this._FreightTotals;
			}
			set
			{
				if ((this._FreightTotals != value))
				{
					this._FreightTotals = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class MyClass2
	{
		
		private System.Nullable<short> _TotalStockUnits;
		
		private string _Product;
		
		public MyClass2()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalStockUnits")]
		public System.Nullable<short> TotalStockUnits
		{
			get
			{
				return this._TotalStockUnits;
			}
			set
			{
				if ((this._TotalStockUnits != value))
				{
					this._TotalStockUnits = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product", CanBeNull=false)]
		public string Product
		{
			get
			{
				return this._Product;
			}
			set
			{
				if ((this._Product != value))
				{
					this._Product = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class MyClass3
	{
		
		private System.Nullable<short> _QuantityPurchased;
		
		private string _Product;
		
		public MyClass3()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuantityPurchased")]
		public System.Nullable<short> QuantityPurchased
		{
			get
			{
				return this._QuantityPurchased;
			}
			set
			{
				if ((this._QuantityPurchased != value))
				{
					this._QuantityPurchased = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product", CanBeNull=false)]
		public string Product
		{
			get
			{
				return this._Product;
			}
			set
			{
				if ((this._Product != value))
				{
					this._Product = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
